# Generated by Django 4.2.11 on 2024-08-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaUsers',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200, unique=True)),
                ('nickname', models.CharField(max_length=200, unique=True)),
                ('coins', models.BigIntegerField()),
                ('gems', models.BigIntegerField()),
            ],
            options={
                'db_table': 'MetaUsers',
            },
        ),
        migrations.DeleteModel(
            name='MetaUser',
        ),
    ]
