# Generated by Django 4.2.11 on 2024-08-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metauser',
            name='coins',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metauser',
            name='gems',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
